name: Update MikroTik YouTube list

on:
  schedule:
    # Каждый день в 02:00 UTC
    - cron: '0 2 * * *'
  # Возможность запустить руками из вкладки Actions
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-list:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generate google_youtube.rsc
        run: python generate_goog_rsc.py

      - name: Commit updated .rsc
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update google_youtube.rsc"
          file_pattern: "google_youtube.rsc"
